### ISSUE TITLE
Consider incorporating RNTV into this.

### ISSUE THREAD

**Issue by lextoumbourou** [DamonToumbourou/plugin.audio.abcradionational#1]
They have some awesome videos at RNTV: http://www.abc.net.au/radionational/rntv/. Would be good to have them incorporated into the plugin.

**Comment by DamonToumbourou** [comment]
Hi Lex,
Thank you for bringing this additional content to my attention. 
I have now developed an addon: pugin.video.abcradionational which incorporates this additional content.
